pattern: "/ITEMS$"
format:
  encoding: "utf-8"
  newline: "\n"
  skip: 0
  delimiter: " "
  doublequote: false
  escapechar: ""
  skipinitialspace: false
  replacers:
    - pattern: "^_$"
      newvalue: ""
table_name: "items"
ddl: |
  drop table if exists {table_name};
  create table {table_name} (
    item_id varchar(3) not null,
    name varchar(255) not null,
    price int not null,
    item_type varchar(1) not null,
    primary key(id)
  );
